name: automerge

on:
  pull_request:

jobs:
  automerge:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: fastify/github-action-merge-dependabot@v2.1.1
        with:
          target: minor
          github-token: ${{ secrets.DEPENDABOT_TOKEN }}